### ISSUE TITLE
available on demand

### ISSUE THREAD

**Issue by FightingFighting** [ejsalin/vlm-probing#1]
Hi, Thank you for your great work.

I got  a question here.

what does this mean "available on demand" ?

how too download "Computing the representations from scratch"?

**Comment by ejsalin** [comment]
Hi, thank you for your interest in our work! 
The method to compute the representations from scratch is available in the README and will enable you to run the probing experiments. The computed representations for each dataset and model are pretty large, this is why we can not have them readily available for downloading. 
However, if you need the representations of a specific task or model, you can use the email to contact me.
